export const CHANGE_NAME = 'CHANGE_NAME';
export const CHANGE_TYPE = 'CHANGE_TYPE';
export const CHANGE_PRICE = 'CHANGE_PRICE';
export const CHANGE_RATING = 'CHANGE_RATING';
export const CHANGE_WARRANTY_YEARS = 'CHANGE_WARRANTY_YEARS';
export const CHANGE_AVAILABLE = 'CHANGE_AVAILABLE';
